files:
  - source: /main/res/raw/changelog_master.md
    translation: /main/res/raw-%two_letters_code%/%original_file_name%
    content_segmentation: 1
  - source: /main/res/raw/changelog_release.md
    translation: /main/res/raw-%two_letters_code%/%original_file_name%
    content_segmentation: 1
